// Visual dashboard for the CLIP vs Gemini Embedding 2 comparison run.
// Data lives in src/data/embedding-comparison.json — generated by
// eval/gemini_embed/compare.py against the live backend.
//
// Renders one section per golden query with three side-by-side columns
// (CLIP / Gemini-768 / Gemini-3072), plus an aggregate scorecard at the top
// so you can see the headline before you scroll.
import Link from "next/link";
import data from "@/data/embedding-comparison.json";

export const metadata = {
  title: "Embedding comparison — CLIP vs Gemini",
};

type Hit = {
  frame_idx: number;
  video_id: string;
  scene_idx: number;
  score: number;
  voice?: string | null;
  voices_present?: string[] | null;
  speakers_count?: string | null;
  recency_days?: number | null;
  judge_score?: number | null;
  judge_reason?: string;
};

type Row = {
  query: string;
  parsed: {
    speaker?: string | null;
    required_speakers?: string[] | null;
    visual_concept?: string | null;
    retrieval_query?: string | null;
    judge_query?: string | null;
    max_age_days?: number | null;
    min_age_days?: number | null;
    speakers_count?: string | null;
  };
  clip:     { latency_ms: number; hits: Hit[] };
  gem_768:  { latency_ms: number; hits: Hit[] };
  gem_3072: { latency_ms: number; hits: Hit[] };
};

type ComparisonData = { queries: Row[]; generated_at: number };

const BACKENDS: Array<{ key: "clip" | "gem_768" | "gem_3072"; label: string; sub: string }> = [
  { key: "clip",     label: "CLIP ViT-L-14",       sub: "open_clip · LAION2B-32B-B82K · local CPU" },
  { key: "gem_768",  label: "Gemini Emb-2 · 768",  sub: "Google Gemini Embedding 2 · 768 dim · API" },
  { key: "gem_3072", label: "Gemini Emb-2 · 3072", sub: "Google Gemini Embedding 2 · 3072 dim · API" },
];

function judgeTone(s?: number | null): string {
  if (s == null) return "bg-zinc-200 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400";
  if (s >= 0.7) return "bg-emerald-100 dark:bg-emerald-900 text-emerald-700 dark:text-emerald-300";
  if (s >= 0.4) return "bg-amber-100 dark:bg-amber-900 text-amber-700 dark:text-amber-300";
  return "bg-red-100 dark:bg-red-900 text-red-700 dark:text-red-300";
}

function aggregate(rows: Row[]) {
  const sum = { clip: 0, gem_768: 0, gem_3072: 0 };
  const visible = { clip: 0, gem_768: 0, gem_3072: 0 };
  const meanK = { clip: 0, gem_768: 0, gem_3072: 0 };
  const latency = { clip: [] as number[], gem_768: [] as number[], gem_3072: [] as number[] };
  for (const row of rows) {
    for (const k of ["clip", "gem_768", "gem_3072"] as const) {
      const hits = row[k].hits;
      const top1 = hits[0]?.judge_score ?? 0;
      sum[k] += top1;
      visible[k] += hits.filter((h) => (h.judge_score ?? 0) >= 0.4).length;
      meanK[k] += hits.reduce((s, h) => s + (h.judge_score ?? 0), 0) / Math.max(1, hits.length);
      latency[k].push(row[k].latency_ms);
    }
  }
  const n = rows.length;
  const lat = (arr: number[]) =>
    Math.round(arr.reduce((a, b) => a + b, 0) / Math.max(1, arr.length));
  // For CLIP, drop the single cold-start outlier so the warm-mean is honest.
  const clipSorted = [...latency.clip].sort((a, b) => a - b);
  const clipWarm = clipSorted.slice(0, -1);
  return {
    sum,
    visible,
    meanK: {
      clip: meanK.clip / n,
      gem_768: meanK.gem_768 / n,
      gem_3072: meanK.gem_3072 / n,
    },
    latency: {
      clip_warm: lat(clipWarm),
      clip_cold: Math.max(...latency.clip),
      gem_768: lat(latency.gem_768),
      gem_3072: lat(latency.gem_3072),
    },
  };
}

function winnerForRow(row: Row): Record<"clip" | "gem_768" | "gem_3072", boolean> {
  const scores = {
    clip: row.clip.hits[0]?.judge_score ?? 0,
    gem_768: row.gem_768.hits[0]?.judge_score ?? 0,
    gem_3072: row.gem_3072.hits[0]?.judge_score ?? 0,
  };
  const max = Math.max(scores.clip, scores.gem_768, scores.gem_3072);
  return {
    clip: scores.clip === max && max > 0,
    gem_768: scores.gem_768 === max && max > 0,
    gem_3072: scores.gem_3072 === max && max > 0,
  };
}

function ParsedChips({ p }: { p: Row["parsed"] }) {
  return (
    <div className="flex flex-wrap gap-1.5 text-[10px]">
      {p.speaker && (
        <span className="rounded-full bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300 px-2 py-0.5">
          speaker: {p.speaker}
        </span>
      )}
      {p.required_speakers && p.required_speakers.length > 1 && (
        <span className="rounded-full bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-300 px-2 py-0.5">
          co-present: {p.required_speakers.join(" + ")}
        </span>
      )}
      {p.visual_concept && (
        <span className="rounded-full bg-purple-50 dark:bg-purple-950 text-purple-700 dark:text-purple-300 px-2 py-0.5">
          visual: {p.visual_concept}
        </span>
      )}
      {p.max_age_days != null && (
        <span className="rounded-full bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 px-2 py-0.5">
          ≤ {p.max_age_days}d
        </span>
      )}
      {p.min_age_days != null && (
        <span className="rounded-full bg-emerald-50 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 px-2 py-0.5">
          ≥ {p.min_age_days}d
        </span>
      )}
      {p.retrieval_query && (
        <span className="rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 px-2 py-0.5">
          retrieval: &ldquo;{p.retrieval_query}&rdquo;
        </span>
      )}
      {p.judge_query !== undefined && (
        <span className="rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 px-2 py-0.5">
          judge: {p.judge_query == null ? "skipped" : `"${p.judge_query}"`}
        </span>
      )}
    </div>
  );
}

function HitCard({ hit, rank }: { hit: Hit; rank: number }) {
  const judge = hit.judge_score;
  const frameUrl = `/api/frames/${hit.video_id}/${String(hit.scene_idx).padStart(4, "0")}`;
  return (
    <div className="rounded-md border border-zinc-200 dark:border-zinc-800 overflow-hidden bg-white dark:bg-zinc-950">
      <div className="relative aspect-video bg-zinc-100 dark:bg-zinc-900">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={frameUrl}
          alt={`${hit.video_id} scene ${hit.scene_idx}`}
          className="w-full h-full object-cover"
        />
        <div className="absolute top-1 left-1 rounded bg-black/70 text-white text-[10px] px-1.5 py-0.5 font-mono">
          #{rank}
        </div>
        {judge != null && (
          <div
            className={`absolute top-1 right-1 rounded ${judgeTone(judge)} text-[10px] px-1.5 py-0.5 font-mono font-semibold`}
          >
            {judge.toFixed(1)}
          </div>
        )}
        <div className="absolute bottom-1 left-1 right-1 flex items-center justify-between text-[10px] font-mono text-white drop-shadow">
          <span className="rounded bg-black/70 px-1 py-0.5">{hit.video_id}</span>
          <span className="rounded bg-black/70 px-1 py-0.5">sc {hit.scene_idx}</span>
        </div>
      </div>
      <div className="p-2 text-[11px] space-y-1">
        <div className="flex flex-wrap gap-1">
          {hit.voice && (
            <span className="rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 px-1.5 py-0.5">
              voice: {hit.voice}
            </span>
          )}
          {hit.speakers_count && (
            <span className="rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 px-1.5 py-0.5">
              {hit.speakers_count}
            </span>
          )}
          {hit.recency_days != null && (
            <span className="rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 px-1.5 py-0.5">
              {hit.recency_days < 30
                ? `${hit.recency_days}d ago`
                : `${Math.round(hit.recency_days / 30)}mo`}
            </span>
          )}
          <span className="rounded bg-zinc-100 dark:bg-zinc-800 text-zinc-500 dark:text-zinc-400 px-1.5 py-0.5 font-mono">
            cos {hit.score.toFixed(3)}
          </span>
        </div>
        {hit.judge_reason && (
          <p className="text-zinc-700 dark:text-zinc-300 italic leading-snug">
            &ldquo;{hit.judge_reason}&rdquo;
          </p>
        )}
      </div>
    </div>
  );
}

function BackendColumn({
  label,
  sub,
  latency,
  hits,
  winner,
}: {
  label: string;
  sub: string;
  latency: number;
  hits: Hit[];
  winner: boolean;
}) {
  return (
    <div
      className={`rounded-xl border p-3 ${
        winner
          ? "border-emerald-400 dark:border-emerald-600 bg-emerald-50/40 dark:bg-emerald-950/20"
          : "border-zinc-200 dark:border-zinc-800"
      }`}
    >
      <div className="mb-3">
        <div className="flex items-center justify-between gap-2">
          <h3 className="text-sm font-semibold">{label}</h3>
          {winner && (
            <span className="rounded-full bg-emerald-600 text-white text-[10px] px-2 py-0.5 font-medium">
              top-1 winner
            </span>
          )}
        </div>
        <p className="text-[10px] text-zinc-500 mt-0.5">{sub}</p>
        <p className="text-[10px] text-zinc-500 mt-0.5 font-mono">latency: {latency} ms</p>
      </div>
      <div className="space-y-2">
        {hits.map((h, i) => (
          <HitCard key={`${h.video_id}-${h.scene_idx}`} hit={h} rank={i + 1} />
        ))}
        {hits.length === 0 && (
          <div className="rounded-md border border-dashed border-zinc-300 dark:border-zinc-700 p-4 text-xs text-zinc-500 text-center">
            no results returned
          </div>
        )}
      </div>
    </div>
  );
}

export default function EmbeddingsPage() {
  const d = data as ComparisonData;
  const agg = aggregate(d.queries);
  const generated = new Date(d.generated_at * 1000).toLocaleString();

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100">
      <main className="mx-auto max-w-7xl px-4 py-10">
        <div className="mb-6 flex items-center justify-between">
          <Link
            href="/"
            className="text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100"
          >
            ← back to search
          </Link>
          <span className="text-[10px] text-zinc-500 font-mono">generated {generated}</span>
        </div>

        <header className="mb-10">
          <h1 className="text-3xl font-semibold tracking-tight">Embedding comparison</h1>
          <p className="mt-2 text-sm text-zinc-500 dark:text-zinc-400">
            CLIP ViT-L-14 vs Gemini Embedding 2 (at 768 and 3072 dimensions) over the six golden
            queries. Same parser, same structural filters, same gpt-4o-mini judge. The only thing
            that changes between columns is the source of the visual frame embedding.
          </p>
        </header>

        {/* Aggregate scorecard */}
        <section className="mb-10 rounded-xl border border-zinc-200 dark:border-zinc-800 p-5">
          <h2 className="text-sm font-semibold uppercase tracking-wider text-zinc-500 mb-4">
            Aggregate over 6 queries
          </h2>
          <div className="grid md:grid-cols-3 gap-4">
            {BACKENDS.map((b) => (
              <div
                key={b.key}
                className="rounded-lg bg-zinc-50 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 p-4"
              >
                <h3 className="font-semibold">{b.label}</h3>
                <p className="text-[11px] text-zinc-500 mb-3">{b.sub}</p>
                <dl className="grid grid-cols-2 gap-3 text-sm">
                  <div>
                    <dt className="text-[10px] uppercase tracking-wider text-zinc-500">
                      sum top-1 judge
                    </dt>
                    <dd className="text-xl font-semibold">
                      {agg.sum[b.key].toFixed(1)}
                      <span className="text-xs font-normal text-zinc-500"> / 6.0</span>
                    </dd>
                  </div>
                  <div>
                    <dt className="text-[10px] uppercase tracking-wider text-zinc-500">
                      visible @5 (judge ≥ 0.4)
                    </dt>
                    <dd className="text-xl font-semibold">
                      {agg.visible[b.key]}
                      <span className="text-xs font-normal text-zinc-500"> / 30</span>
                    </dd>
                  </div>
                  <div>
                    <dt className="text-[10px] uppercase tracking-wider text-zinc-500">
                      mean judge over top-5
                    </dt>
                    <dd className="text-xl font-semibold">{agg.meanK[b.key].toFixed(2)}</dd>
                  </div>
                  <div>
                    <dt className="text-[10px] uppercase tracking-wider text-zinc-500">
                      mean latency
                    </dt>
                    <dd className="text-xl font-semibold font-mono">
                      {b.key === "clip" ? `${agg.latency.clip_warm} ms` : null}
                      {b.key === "gem_768" ? `${agg.latency.gem_768} ms` : null}
                      {b.key === "gem_3072" ? `${agg.latency.gem_3072} ms` : null}
                    </dd>
                    {b.key === "clip" && (
                      <p className="text-[10px] text-zinc-400 font-mono">
                        cold first call: {agg.latency.clip_cold} ms (HF tokenizer load)
                      </p>
                    )}
                  </div>
                </dl>
              </div>
            ))}
          </div>

          <div className="mt-6 grid md:grid-cols-3 gap-4 text-xs">
            <div className="rounded-lg border border-zinc-200 dark:border-zinc-800 p-3">
              <p className="text-[10px] uppercase tracking-wider text-zinc-500 mb-1">
                Per-query winners (top-1 judge)
              </p>
              <p className="text-zinc-700 dark:text-zinc-300 leading-relaxed">
                CLIP wins <strong>3</strong> · Gemini wins <strong>2</strong> · tied <strong>1</strong>.
                Identical top-1 sum (3.5 / 6.0). Gemini surfaces two more visible-tier results
                across the union of top-5.
              </p>
            </div>
            <div className="rounded-lg border border-zinc-200 dark:border-zinc-800 p-3">
              <p className="text-[10px] uppercase tracking-wider text-zinc-500 mb-1">
                768 vs 3072
              </p>
              <p className="text-zinc-700 dark:text-zinc-300 leading-relaxed">
                Identical top-K in 5 of 6 queries. The single difference scores the same. No
                quality lift from the larger vectors on this corpus. 3072 storage is 170 MB vs
                43 MB for 768.
              </p>
            </div>
            <div className="rounded-lg border border-zinc-200 dark:border-zinc-800 p-3">
              <p className="text-[10px] uppercase tracking-wider text-zinc-500 mb-1">
                Cost
              </p>
              <p className="text-zinc-700 dark:text-zinc-300 leading-relaxed">
                One-time bake: $1.87 per dim. CLIP per query: $0 (local CPU). Gemini per query:
                ≈ $0.00003 (text-embed of the retrieval string).
              </p>
            </div>
          </div>
        </section>

        {/* Per-query side-by-side */}
        <div className="space-y-12">
          {d.queries.map((row) => {
            const win = winnerForRow(row);
            return (
              <section
                key={row.query}
                className="border-t border-zinc-200 dark:border-zinc-800 pt-8"
              >
                <h2 className="text-lg font-semibold mb-2">&ldquo;{row.query}&rdquo;</h2>
                <ParsedChips p={row.parsed} />
                <div className="mt-4 grid md:grid-cols-3 gap-4">
                  {BACKENDS.map((b) => (
                    <BackendColumn
                      key={b.key}
                      label={b.label}
                      sub={b.sub}
                      latency={row[b.key].latency_ms}
                      hits={row[b.key].hits}
                      winner={win[b.key]}
                    />
                  ))}
                </div>
              </section>
            );
          })}
        </div>
      </main>
    </div>
  );
}
